CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  nombre VARCHAR(100) NOT NULL DEFAULT '',
  created BIGINT NOT NULL
);

ALTER TABLE items ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE items DROP COLUMN IF EXISTS monto;
ALTER TABLE items DROP COLUMN IF EXISTS periodicidad;
ALTER TABLE items DROP COLUMN IF EXISTS meta;
ALTER TABLE items DROP COLUMN IF EXISTS acumulado;
ALTER TABLE items DROP COLUMN IF EXISTS productos;

CREATE INDEX IF NOT EXISTS idx_items_user_id ON items(user_id);

ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token VARCHAR(64) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token_at BIGINT DEFAULT 0;

CREATE TABLE IF NOT EXISTS items_finanza (
  id VARCHAR(36) PRIMARY KEY REFERENCES items(id) ON DELETE CASCADE,
  monto DECIMAL(12,2) NOT NULL DEFAULT 0,
  periodicidad VARCHAR(20) DEFAULT NULL,
  meta DECIMAL(12,2) NOT NULL DEFAULT 0,
  acumulado DECIMAL(12,2) NOT NULL DEFAULT 0,
  cantidad INTEGER NOT NULL DEFAULT 1,
  precio_unitario DECIMAL(12,2) NOT NULL DEFAULT 0
);
