CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  nombre VARCHAR(100) NOT NULL DEFAULT '',
  created BIGINT NOT NULL
);

ALTER TABLE items ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE items ADD COLUMN IF NOT EXISTS productos TEXT DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_items_user_id ON items(user_id);

ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token VARCHAR(64) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_token_at BIGINT DEFAULT 0;
